import { createFileRoute } from "@tanstack/react-router";
import { Coffee, Compass, Eye, MessageCircle } from "lucide-react";
import { ComicPanel, SectionTitle, SpeechBubble, Tag } from "@/components/portfolio-ui";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About — Fatma Mourad" }, { name: "description", content: "Meet Fatma Mourad, a product designer who makes complicated things feel clear and human." },
  { property: "og:title", content: "About Fatma Mourad" }, { property: "og:description", content: "Product designer, systems thinker, curious observer." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: AboutPage });

function AboutPage() { return <div className="page-shell about-page"><SectionTitle eyebrow="Behind the screens" index="03">Curious by nature.<br/><em>Designer by practice.</em></SectionTitle><div className="about-story"><div className="portrait-scene" aria-label="An illustrated abstract portrait of Fatma"><div className="portrait-head"><div className="portrait-hair"/><div className="portrait-face"/></div><div className="portrait-body"/><span className="doodle-star">✦</span><SpeechBubble>I’m always asking:<br/><strong>“What are we really solving?”</strong></SpeechBubble></div><div className="about-copy"><p className="lead">I’m Fatma, a product designer who likes finding the calm, logical thread inside messy problems.</p><p>I work from observation to outcome: listening closely, mapping systems, prototyping early, and making every detail earn its place. My best work helps people move forward without having to think about the interface at all.</p><p>Currently based in Cairo, collaborating everywhere.</p></div></div><div className="philosophy-grid"><ComicPanel><Eye/><span>01</span><h2>Notice deeply</h2><p>The useful clues are often hiding in plain sight.</p></ComicPanel><ComicPanel><Compass/><span>02</span><h2>Frame clearly</h2><p>A strong question can save a team months of motion.</p></ComicPanel><ComicPanel><MessageCircle/><span>03</span><h2>Make together</h2><p>Design gets better when the room has many voices.</p></ComicPanel></div><section className="about-details"><div><h2>What I do</h2><div className="tag-cloud">{["Product strategy","User research","Interaction design","Prototyping","Design systems","Facilitation"].map(x=><Tag key={x}>{x}</Tag>)}</div></div><div><h2>Tools in rotation</h2><p>Figma · FigJam · Framer · Notion · Maze · Dovetail</p></div><div className="personal-note"><Coffee/><p>Offline, I’m usually sketching strangers in cafés, collecting oddly specific maps, or trying to perfect one more pasta recipe.</p></div></section></div>; }
