import { createFileRoute } from "@tanstack/react-router";
import { Download } from "lucide-react";
import { SectionTitle, Tag } from "@/components/portfolio-ui";

export const Route = createFileRoute("/resume")({ head: () => ({ meta: [
  { title: "Resume — Fatma Mourad" }, { name: "description", content: "Experience, education, and capabilities of product designer Fatma Mourad." },
  { property: "og:title", content: "Resume — Fatma Mourad" }, { property: "og:description", content: "Product design experience across complex services and human-centered digital products." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" },
]}), component: ResumePage });
const roles=[{years:"2024—NOW",title:"Senior Product Designer",company:"Independent · Cairo & remote",text:"Leading product strategy and end-to-end design for teams in mobility, health, and climate."},{years:"2021—2024",title:"Product Designer",company:"North Studio · Cairo",text:"Shipped cross-platform products, facilitated discovery, and helped establish a shared design system."},{years:"2019—2021",title:"UX Designer",company:"Tangent Digital · Cairo",text:"Translated research into practical flows and prototypes for early-stage digital services."}];
function ResumePage(){return <div className="page-shell resume-page"><SectionTitle eyebrow="The practical bits" index="04">Experience,<br/><em>on paper.</em></SectionTitle><div className="resume-actions"><p>I design digital products from the first ambiguous question to the final polished interaction.</p><a className="download-button" href="mailto:fatma@example.com?subject=Resume request"><Download/> Request PDF</a></div><div className="resume-sheet"><section><h2>Experience</h2><div className="timeline">{roles.map((role,i)=><article key={role.title}><span className="timeline-dot">{i+1}</span><p className="timeline-year">{role.years}</p><div><h3>{role.title}</h3><strong>{role.company}</strong><p>{role.text}</p></div></article>)}</div></section><aside><div><h2>Capabilities</h2><div className="tag-cloud">{["Research","Strategy","IA","Flows","Prototypes","Systems","Workshops","Testing"].map(x=><Tag key={x}>{x}</Tag>)}</div></div><div><h2>Education</h2><h3>BSc, Applied Arts</h3><p>Visual Communication<br/>Helwan University</p></div><div><h2>Languages</h2><p>Arabic — Native<br/>English — Fluent</p></div></aside></div></div>}
